# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
        ('cars_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='cars',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='login_app.User'),
        ),
    ]
