# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 21:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_app', '0003_auto_20170926_1456'),
        ('cars_app', '0003_auto_20170926_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(max_length=255)),
                ('car_model', models.CharField(max_length=255)),
                ('year', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('cars', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='login_app.User')),
            ],
        ),
    ]
